/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as MainImport } from './routes/_main'
import { Route as AuthSignupImport } from './routes/auth.signup'
import { Route as AuthSigninImport } from './routes/auth.signin'
import { Route as AuthMagicLinkImport } from './routes/auth.magic-link'
import { Route as AuthForgotPasswordImport } from './routes/auth.forgot-password'
import { Route as MainSettingsImport } from './routes/_main.settings'
import { Route as MainMeImport } from './routes/_main.me'
import { Route as AuthResetPasswordTokenImport } from './routes/auth.reset-password.$token'
import { Route as MainSettingsProfileImport } from './routes/_main.settings.profile'
import { Route as MainSettingsAccountImport } from './routes/_main.settings.account'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const MainRoute = MainImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthSignupRoute = AuthSignupImport.update({
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

const AuthMagicLinkRoute = AuthMagicLinkImport.update({
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const MainSettingsRoute = MainSettingsImport.update({
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)

const MainMeRoute = MainMeImport.update({
  path: '/me',
  getParentRoute: () => MainRoute,
} as any)

const AuthResetPasswordTokenRoute = AuthResetPasswordTokenImport.update({
  path: '/reset-password/$token',
  getParentRoute: () => AuthRoute,
} as any)

const MainSettingsProfileRoute = MainSettingsProfileImport.update({
  path: '/profile',
  getParentRoute: () => MainSettingsRoute,
} as any)

const MainSettingsAccountRoute = MainSettingsAccountImport.update({
  path: '/account',
  getParentRoute: () => MainSettingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_main/me': {
      id: '/_main/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MainMeImport
      parentRoute: typeof MainImport
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsImport
      parentRoute: typeof MainImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkImport
      parentRoute: typeof AuthImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof AuthImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthImport
    }
    '/_main/settings/account': {
      id: '/_main/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof MainSettingsAccountImport
      parentRoute: typeof MainSettingsImport
    }
    '/_main/settings/profile': {
      id: '/_main/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof MainSettingsProfileImport
      parentRoute: typeof MainSettingsImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MainRoute: MainRoute.addChildren({
    MainMeRoute,
    MainSettingsRoute: MainSettingsRoute.addChildren({
      MainSettingsAccountRoute,
      MainSettingsProfileRoute,
    }),
  }),
  AuthRoute: AuthRoute.addChildren({
    AuthForgotPasswordRoute,
    AuthMagicLinkRoute,
    AuthSigninRoute,
    AuthSignupRoute,
    AuthResetPasswordTokenRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_main",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_main": {
      "filePath": "_main.tsx",
      "children": [
        "/_main/me",
        "/_main/settings"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/forgot-password",
        "/auth/magic-link",
        "/auth/signin",
        "/auth/signup",
        "/auth/reset-password/$token"
      ]
    },
    "/_main/me": {
      "filePath": "_main.me.tsx",
      "parent": "/_main"
    },
    "/_main/settings": {
      "filePath": "_main.settings.tsx",
      "parent": "/_main",
      "children": [
        "/_main/settings/account",
        "/_main/settings/profile"
      ]
    },
    "/auth/forgot-password": {
      "filePath": "auth.forgot-password.tsx",
      "parent": "/auth"
    },
    "/auth/magic-link": {
      "filePath": "auth.magic-link.tsx",
      "parent": "/auth"
    },
    "/auth/signin": {
      "filePath": "auth.signin.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth.signup.tsx",
      "parent": "/auth"
    },
    "/_main/settings/account": {
      "filePath": "_main.settings.account.tsx",
      "parent": "/_main/settings"
    },
    "/_main/settings/profile": {
      "filePath": "_main.settings.profile.tsx",
      "parent": "/_main/settings"
    },
    "/auth/reset-password/$token": {
      "filePath": "auth.reset-password.$token.tsx",
      "parent": "/auth"
    }
  }
}
ROUTE_MANIFEST_END */
